name: kwadra
description: "The UI pillar of Kwadra project"
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  http: ^1.2.1
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  go_router: ^14.1.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
